### PR TITLE
Allow IQ input for rtl_fm  support.

### PR DESCRIPTION
**Pull request by ED6E0F17**
Allows headless decoding on similar setups used to track radiosondes.

Imports codec2 source code for convenience, and adds example code to launch rtl-fm.

The pass-band margin for tuning is still quite narrow, just over 1 ppm either side of the sweet spot, so it would be helpful if the codec2 modem could put out frequency info to be passed into  a web interface like the useful and most excellent radiosonde-autorx server.

### CODE REVIEW

**Comment by darksidelemm** [comment]
Very cool! 
There have been some changes to the upstream fsk_demod that might be useful to deal with the current narrow frequency estimation range. The main one is the ability to set a frequency estimator range, which I'm using in the current testing branch of auto_rx: https://github.com/projecthorus/radiosonde_auto_rx/blob/testing/utils/fsk_demod.c#L216

I've done some cursory testing on the changes, and they work fine. Nice work!

**Comment by darksidelemm** [comment]
Oh, it also might be worth submitting a PR with these changes into the codec2 git repo: https://github.com/drowe67/codec2/

**Comment by darksidelemm** [comment]
@ED6E0F17 Hi - not sure how to contact you, hence pinging you here.

I've noticed you are running auto_rx version 1.2.3-beta17, which suggests you are running your own fork with other changes. I'm wondering what these changes are, and if you are planning on submitting a PR with them?

**Comment by ED6E0F17** [comment]
Hi,

I  don`t read emails or github notifications, so I try not to submit pull request or open issues. Sometimes I forget.

I made some small UI changes to auto_rx to get things more to my liking, and some work arounds because my fork of rtl_fm only runs at 48kHz, which really messes with your code. I don`t want to change that because I hate re-sampling; you use a lower samplerate because rtl_fm does not have a lowpass filter on the input for FM.

Thanks for the code, I had a great retrieve yesterday - but I noticed there was a 10 minute lag on habhub by the time it burst.

**Comment by darksidelemm** [comment]
Most of the decoders have switched to using IQ input now, and almost all of
those run at 48 kHz IQ, so 48 kHz is fine for the most part...

What UI changes in particular?

Also, if you're going to continue using your fork, please make sure you
stay up-to-date with some non-backwards-compatible changes that will be
release soon.

Cheers,
Mark

**Pull request merged**
